### ISSUE TITLE
Error on addon loading, heal prediction not working

### ISSUE THREAD

**Issue by Cephel** [Aviana/HealComm#10]
![](https://i.imgur.com/20ISlOB.png)

happens in https://github.com/Aviana/HealComm/blob/master/libs/HealComm-1.0/HealComm-1.0.lua#L23

Addons running:
- pfUI
- HealComm

**Comment by Road-block** [comment]
This is caused by either

- Another addon loading a Babble-Spell-2.2 with a higher/same minor revision as the one HealComm-1.0 embeds that is missing some of the entries HealComm references.
- Updating by overwriting and not fully exiting and restarting the client.

The first cause can be mitigated by incrementing the minor revision in the embedded Babble-Spell-2.2 when new entries are added to make it more likely it is not discarded by the AceLibrary upgrade process.  
Ultimately there is no surefire solution because there are too many library versions out in the wild and other authors can also bump the minor revision.

**Comment by Cephel** [comment]
Like I said above, the _only_ addons running were pfUI and HealComm, pfUI referred me here from the ticket referenced above.

It is likely that this only affects the library version of HealComm, not the embededded Luna version.

**Comment by Road-block** [comment]
> the only addons running were pfUI and HealComm

This is literally impossible if you didn't update without restarting the client (option •1 above on what could be the cause of this error)  
If you updated without restarting the client (WoW can't recognize new files while it's running) then this would be a one-time error that would not happen again after you have exited the game and started for subsequent times.

The error is on
https://github.com/Aviana/HealComm/blob/0fe6432704288abf67a9959bbd9a143a7e16011c/libs/Babble-Spell-2.2/Babble-Spell-2.2.lua#L943
which as you can see is present in the embedded Babble-Spell-2.2 library.  
And the library is properly referenced in https://github.com/Aviana/HealComm/blob/0fe6432704288abf67a9959bbd9a143a7e16011c/HealComm.toc#L16
so it will load.

If the error is still happening **after you have exited and restarted your client** do me a favor and make a search for `Babble-Spell` in your AddOns folder, I guarantee you, you will find another version.

**Comment by Road-block** [comment]
Just to add for Aviana's benefit, AceLibrary will load and then discard dependent libraries (like Babble-Spell-2.2) based on their https://github.com/Aviana/HealComm/blob/0fe6432704288abf67a9959bbd9a143a7e16011c/libs/Babble-Spell-2.2/Babble-Spell-2.2.lua#L13 minor version so only the most *recent* copy remains in memory.  
When you manually add a spell to the library at the least you should increment the revision number.  
It's not a guarantee because like I said above there is no longer a mainline for Ace addons that every author is using and other authors can mess with revision numbers too.  
But it's better than not incrementing because when revision numbers are equal which library remains in memory comes down to loading order.

**Comment by Aviana** [comment]
Thanks for your efforts @Road-block, but this isn't about revision numbers. The BabbleSpell library simbly isn't there for him. Maybe he caught a version where i forgot to include it.

So to solve this simply exit the client, download 1.11 and dump it into your addons folder.

**Comment by Cephel** [comment]
Like I said above, the _only_ addons running were pfUI and HealComm, pfUI referred me here from the ticket referenced above.

It is likely that this only affects the library version of HealComm, not the embededded Luna version.

**Comment by Cephel** [comment]
Issue persists with a fresh check out and only the 2 addons running, fresh client restart.

HealComm at 0fe6432
pfUI at 5243fed

**Comment by Cephel** [comment]
Correction, error is slightly altered: ![](https://i.imgur.com/B4j4TWf.png)

**Comment by Road-block** [comment]
Get a proper error reporting addon like [BugGrabber](http://addons.us.to/addon/buggrabber) and post the full error stack.

**Comment by Cephel** [comment]
Seems this issue was resolved by 08a726dc901e6a9918a4f79085915952eff3b114

**Comment by Cephel** [comment]
Nope, it wasn't.
